### ISSUE TITLE
No module named setuptools

### ISSUE THREAD

**Issue by jdub** [servo/homebrew-servo#7]
I'm getting the following error when attempting to `brew install --HEAD servo/servo/servo`:

```
==> Installing servo from servo/servo
==> Cloning https://github.com/servo/servo.git
Updating /Library/Caches/Homebrew/servo--git
==> Checking out branch master
==> Downloading https://pypi.python.org/packages/source/v/virtualenv/virtualenv-13.1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/servo--virtualenv-13.1.2.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/servo20160223-910
Last 15 lines from /Users/jdub/Library/Logs/Homebrew/servo/01.python:
python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/servo20160223-91077-107yxy2/_vedir
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named setuptools

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/servo/homebrew-servo/issues
```

The just-installed Python 2.7 is the default python:

```
$ which python
/usr/local/bin/python

$ python
Python 2.7.10 (default, Oct 23 2015, 18:05:06)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named setuptools
```

**Comment by jdub** [comment]
> The just-installed Python 2.7 is the default 

Hold on, no it's not! I'll try again in a new shell:

```
$ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named setuptools
```

Looks better. Sort of. Let's see if the brew install environment sorts it out…

**Comment by jdub** [comment]
Failed again. Same error.

**Comment by larsbergstrom** [comment]
Interesting! Thanks for taking the time to report it.

Can you please try first running `brew update` twice and then `brew doctor`? Like their troubleshooting page (https://github.com/Homebrew/homebrew/tree/master/share/doc/homebrew#troubleshooting), we've seen that many brew issues are related to either needing to update or files getting into a strange state - particularly if you had a homebew install and then upgraded OSX versions.

Sorry this didn't work out of box for you!

**Comment by jdub** [comment]
No worries. The suggestion from This Week in Servo was hard to resist. :smile: 

```
$ brew update
Already up-to-date.
$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
```

This seems kinda odd:

```
jdub@slender:~$ python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/Library/Python/2.7/site-packages/pip-1.3.1-py2.7.egg', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Python/2.7/site-packages']
```

**Comment by larsbergstrom** [comment]
Yeah, my path looks pretty different. Are you getting the default python instead of the homebrew one?

```
[larsberg@lbergstrom ~]$ python
Python 2.7.11 (default, Jan 11 2016, 12:48:10) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages/PyObjC', '/Library/Python/2.7/site-packages']
>>> 
[larsberg@lbergstrom ~]$ which python
/usr/local/bin/python
[larsberg@lbergstrom ~]$ 
```

**Comment by jdub** [comment]
Yeah, it was definitely using the brew python… it looks like a `brew uninstall python` and reinstall spin fixed up the path issues, and now the servo build is bounding away through mach.

Thanks for your help. I reckon this might be a brew heisenbug, so I'll close this now. :smile:

**Comment by larsbergstrom** [comment]
@jdub Thanks for coming back and filling in the info on how you fixed it! If anybody else runs into it, now the solution will be here :-)
